# Ejército ficticio: filtrado y ordenación

In [1]:
import pandas as pd

### Paso 2. Estos son los datos proporcionados en un diccionario

In [12]:
# Creamos un DataFrame de ejemplo sobre un ejército ficticio
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Paso 3. Crea un DataFrame y asígnalo a una variable llamada army.

In [ ]:
army = pd.DataFrame(raw_data)

### Paso 4. Establece la columna 'origin' como índice del DataFrame.

In [21]:
army = pd.DataFrame(raw_data).set_index('origin')

### Paso 5. Muestra únicamente la columna veterans.

In [25]:
army["veterans"]

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

### Paso 6. Muestra las columnas veterans y deaths.

In [31]:
army[["veterans", "deaths"]]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

### Paso 7. Muestra los nombres de todas las columnas.

In [32]:
list(army.columns)

['regiment',
 'company',
 'deaths',
 'battles',
 'size',
 'veterans',
 'readiness',
 'armored',
 'deserters']

### Paso 8. Selecciona las columnas deaths, size y deserters para Maine y Alaska.

In [ ]:
army.loc[["Maine","Alaska"],["deaths", "size", "deserters"]]#el orden importa, primero filas y despues columnas

        deaths  size  deserters
origin
Maine       43  1592          3
Alaska     523   987         24

### Paso 9. Selecciona las filas de la 3 a la 7 y las columnas de la 3 a la 6.

In [44]:
army.iloc[3,7],[3,6]

(np.int64(1), [3, 6])

### Paso 10. Selecciona todas las filas posteriores a la cuarta y todas las columnas.

In [51]:
army.iloc [4,],list(army.columns)

(regiment     Dragoons
 company           1st
 deaths             43
 battles             4
 size             1592
 veterans           73
 readiness           2
 armored             0
 deserters           3
 Name: Maine, dtype: object,
 ['regiment',
  'company',
  'deaths',
  'battles',
  'size',
  'veterans',
  'readiness',
  'armored',
  'deserters'])

### Paso 11. Selecciona todas las filas hasta la cuarta, incluida, y todas las columnas.

In [55]:
army.iloc[:5],list(army.columns)

(              regiment company  deaths  battles  size  veterans  readiness  \
 origin
 Arizona     Nighthawks     1st     523        5  1045         1          1
 California  Nighthawks     1st      52       42   957         5          2
 Texas       Nighthawks     2nd      25        2  1099        62          3
 Florida     Nighthawks     2nd     616        2  1400        26          3
 Maine         Dragoons     1st      43        4  1592        73          2

             armored  deserters
 origin
 Arizona           1          4
 California        0         24
 Texas             1         31
 Florida           1          2
 Maine             0          3  ,
 ['regiment',
  'company',
  'deaths',
  'battles',
  'size',
  'veterans',
  'readiness',
  'armored',
  'deserters'])

### Paso 12. Selecciona desde la tercera columna hasta la séptima.

In [58]:
army.iloc[:, 2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

### Paso 13. Selecciona las filas en las que army.deaths sea mayor que 50.

In [60]:

army['deaths'] > 50

origin
Arizona        True
California     True
Texas         False
Florida        True
Maine         False
Iowa           True
Alaska         True
Washington     True
Oregon         True
Wyoming        True
Louisana      False
Georgia       False
Name: deaths, dtype: bool

### Paso 14. Selecciona las filas en las que army.deaths sea mayor que 500 o menor que 50.

In [64]:
army[(army['deaths'] > 50) & (army['deaths'] < 500)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
California,Nighthawks,1st,52,42,957,5,2,0,24
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

### Paso 15. Selecciona todos los regimientos cuyo nombre no sea «Dragoons».

In [65]:
army[army['regiment'] != 'Dragoons']

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Paso 16. Selecciona las filas con índice Texas y Arizona.

In [66]:
army.loc[['Texas', 'Arizona']]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

### Paso 17. Selecciona la tercera celda de la fila cuyo índice es Arizona.

In [67]:
army.loc['Arizona'].iloc[2]

np.int64(523)

### Paso 18. Selecciona la tercera celda de la columna deaths.

KeyError: 'deaths'