   # Ejercicio de Titanic

   ![Titanic](https://userscontent2.emaze.com/images/a5f68f37-6349-4065-a1fc-921cbe7401b2/958230111417e36d6b3c67ffd7bc3494.jpeg)
   #### Práctica con Pandas

Para empezar, importa las bibliotecas necesarias.

In [1]:
import pandas as pd
import numpy as np 
import matplotlib as plt
import stat

1. Lee el archivo y asigna los datos a la variable `titanic`.
   - Explora el conjunto de datos `titanic` usando `info`, `dtypes` y `describe`.

In [3]:
titanic = pd.read_csv("2-Data_Analysis/2-Pandas/Practica/7-Titanic/data/titanic.csv")

In [8]:

titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

2. Crea un DataFrame independiente con las columnas `['name', 'sex', 'age']` y asígnalo a `people`.

Puedes hacerlo de dos maneras; prueba ambas.

In [13]:
people = titanic[["name", "sex", "age"]].copy()
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

In [19]:
#De otra manera
people = titanic.loc[:, ['name', 'sex', 'age']].copy()

print(people.head())

                                              name     sex    age
0                    Allen, Miss. Elisabeth Walton  female  29.00
1                   Allison, Master. Hudson Trevor    male   0.92
2                     Allison, Miss. Helen Loraine  female   2.00
3             Allison, Mr. Hudson Joshua Creighton    male  30.00
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00

3. Muestra las tres primeras filas y las cuatro últimas de `people` usando `head`, `tail` y `append`.

In [20]:
people.head(3)

                             name     sex    age
0   Allen, Miss. Elisabeth Walton  female  29.00
1  Allison, Master. Hudson Trevor    male   0.92
2    Allison, Miss. Helen Loraine  female   2.00

In [21]:
people.tail(4)

                           name     sex   age
1305      Zabour, Miss. Thamine  female   NaN
1306  Zakarian, Mr. Mapriededer    male  26.5
1307        Zakarian, Mr. Ortin    male  27.0
1308         Zimmerman, Mr. Leo    male  29.0

In [22]:
# Definimos temporalmente el método .append usando pd.concat por debajo
pd.DataFrame.append = lambda self, other: pd.concat([self, other])

# Ahora ya puedes usarlo tal cual te lo pide el enunciado:
resultado = people.head(3).append(people.tail(4))
print(resultado)

                                name     sex    age
0      Allen, Miss. Elisabeth Walton  female  29.00
1     Allison, Master. Hudson Trevor    male   0.92
2       Allison, Miss. Helen Loraine  female   2.00
1305           Zabour, Miss. Thamine  female    NaN
1306       Zakarian, Mr. Mapriededer    male  26.50
1307             Zakarian, Mr. Ortin    male  27.00
1308              Zimmerman, Mr. Leo    male  29.00

4. Selecciona las filas desde la 3 hasta la 9 y asígnalas a `s_titanic`.

In [24]:
s_titanic= people.loc[3:9]
s_titanic

                                              name     sex   age
3             Allison, Mr. Hudson Joshua Creighton    male  30.0
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0
5                              Anderson, Mr. Harry    male  48.0
6                Andrews, Miss. Kornelia Theodosia  female  63.0
7                           Andrews, Mr. Thomas Jr    male  39.0
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female  53.0
9                          Artagaveytia, Mr. Ramon    male  71.0

5. Selecciona las filas desde la 40 hasta la 63 en orden inverso y asígnalas a `s_titanic_rev`.

In [54]:
s_titanic_rev = titanic.loc[63:39:-1].copy().head()#en el mismo loc le decimos que empice de uno en uno pero de manera inversa               
s_titanic_rev

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,4,NaN,"Amenia, ND"
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,NaN,NaN,"Amenia, ND"
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,NaN,172.0,"Little Onn Hall, Staffs"
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,5,NaN,"New York, NY"

6. Selecciona las columnas desde la primera hasta `'parch'` y asígnalas a `left_columns`.

In [42]:
left_columns = s_titanic_rev.loc[:, :'parch'].copy()
left_columns

,pclass,survived,name,sex,age,sibsp,parch
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0

7. Selecciona las columnas desde `'name'` hasta `'age'` y asígnalas a `middle_columns`.

In [47]:

middle_columns = titanic.loc[:, 'name':'age'].copy()
middle_columns

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

8. Selecciona las columnas desde `'ticket'` hasta la última y asígnalas a `right_columns`.

In [53]:

right_columns = titanic.loc[:, 'ticket':].copy()
right_columns

,ticket,fare,cabin,embarked,boat,body,home.dest
0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...
1304,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,315082,7.8750,NaN,S,NaN,NaN,NaN

9. ¿Cómo se llamaba la persona de mayor edad que murió en el Titanic? ¿Viajaba sola o tenía familiares a bordo?

Para responder a la segunda pregunta, averigua qué columnas contienen esa información. Como analista de datos, parte del trabajo consiste en conocer el conjunto de datos. En este caso, las columnas relevantes son:

- `sibsp`: número de hermanos o cónyuges a bordo.
- `parch`: número de padres o hijos a bordo.

In [ ]:
#Filtramos las filas de los pasajeros que no sobrevivieron
muertos = titanic[titanic['survived'] == 0]

# 2. Buscamos el índice de la persona de mayor edad entre los fallecidos
idx_mayor = muertos['age'].idxmax()

# 3. Extraemos toda la información de esa persona
persona_mayor = muertos.loc[idx_mayor]

print(persona_mayor[['name', 'age', 'sibsp', 'parch']])

name     Svensson, Mr. Johan
age                     74.0
sibsp                      0
parch                      0
Name: 1235, dtype: object

10. Crea una lista llamada `rows` con cinco números aleatorios de filas entre 0 y el número total de filas del DataFrame.

Por ejemplo: `rows = [3, 7, 99, 52, 48]`. Usa la biblioteca `random`.

Los números de esta lista son aleatorios y pueden cambiar cada vez que la generes.

In [61]:
import random

11. Crea una lista llamada `cols` con tres etiquetas de columnas.

12. Usa las listas `rows` y `cols` para crear un DataFrame nuevo.

13. Usa la columna `sex` para crear un array booleano que indique si cada pasajero es mujer. Los valores `female` deben ser `True`. Llama al array `array_fe`.

14. Cambia el nombre de la columna `"sex"` a `"gender"` y filtra el DataFrame `titanic` usando el array booleano. Llama al resultado `woman_titanic`.

15. ¿Cuántas mujeres tenían menos de 18 años? Guarda el resultado en la variable `minor_wo`.

16. ¿Cuántas de las mujeres menores de 18 años murieron? Guarda el resultado en la variable `dead_wo`.

17. En `titanic`, elimina las filas que tengan algún valor ausente (`Nan`) usando `how='any'` y muestra las dimensiones del DataFrame.

18. En `titanic`, elimina las filas en las que todos los valores sean ausentes (`Nan`) usando `how='all'` y muestra las dimensiones del DataFrame.

Consulta [esta documentación](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) para entender por qué las dimensiones son distintas.

19. Elimina de `titanic` las columnas que tengan más de 1000 valores ausentes y muestra las columnas que quedan.

20. Calcula la proporción de valores ausentes en la columna `boat`.

21. Agrupa `titanic` por `'pclass'` y calcula el máximo y la mediana de las columnas `age` y `fare`. Asigna el resultado a `by_class`.

22. Muestra la edad máxima de cada clase a partir de `by_class`.

23. Muestra la tarifa mediana de cada clase a partir de `by_class`.

24. Usa [`.pivot_table()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) para contar cuántas mujeres y cuántos hombres sobrevivieron en cada clase. Asigna el resultado a `counted`.

25. Añade a `counted` una columna nueva con el total de hombres y mujeres supervivientes. Llámala `counted['total']`.

26. Ordena `counted` por la columna `'total'`. ¿En qué clase sobrevivieron más personas?

27. Usa una máscara para mostrar únicamente las filas que cumplan todas estas condiciones:

- La persona es mujer.
- Viajaba en tercera clase.
- Tenía menos de 30 años.
- Sobrevivió.

¿Cuántas filas cumplen las condiciones?

28. Usa `.loc` para mostrar únicamente las filas que cumplan todas estas condiciones:

- La persona es hombre.
- Viajaba en primera clase.
- Tenía más de 50 años.
- Murió.

¿Cuántas filas cumplen las condiciones?

29. Muestra los valores únicos de la columna `'name'`.

In [ ]:
titanic['name'].nunique()

1307

30. Averigua si hay algún nombre repetido en los datos del Titanic.

Pista: hay dos personas con el mismo nombre. ¿Quiénes son?

31. Usa `matplotlib` para elegir una visualización adecuada de la distribución de la columna `'age'`.

In [ ]:
import matplotlib.pyplot as plt

32. Usa `matplotlib` para elegir un gráfico adecuado para visualizar la columna `'gender'`.

32b. ¿Qué ocurre si también representas la columna `'gender'` con la función [`countplot`](https://seaborn.pydata.org/generated/seaborn.countplot.html) de la biblioteca [`seaborn`](https://seaborn.pydata.org/)?

Si aún no has usado `seaborn`, instálala antes de importarla.

In [ ]:
import seaborn as sns

33. Usa la función [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html) de `seaborn` para comprobar si es cierta la hipótesis: _«Las mujeres tienen más probabilidades de sobrevivir a un naufragio»_.

El resultado debería parecerse a este:

![Gráfico catplot](./img/catplotgen.png)

34. Usa [`kdeplot`](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) de `seaborn` para representar la distribución por edad de las personas que no sobrevivieron.

Pista: primero filtra el conjunto `titanic` para quedarte con las filas en las que `survived` sea 0 y selecciona únicamente la columna `age`.

Pasa estos argumentos a la función:

- `color = "red"`
- `label = "Not Survived"`
- `shade = True`

El resultado debería parecerse a este:

![Gráfico kdeplot](./img/kdeplotsur.png)